import { BaseElement } from './baseElement';

const LOREM_IPSUM = `God help us, we're in the hands of engineers. You're a very talented young man, with your own clever thoughts and ideas. Do you need a manager? Life finds a way. My dad once told me, laugh and the world laughs with you, Cry, and I'll give you something to cry about you little bastard! Forget the fat lady! You're obsessed with the fat lady! Drive us out of here! I was part of something special. I was part of something special. We gotta burn the rain forest, dump toxic waste, pollute the air, and rip up the OZONE! 'Cause maybe if we screw up this planet enough, they won't want it anymore!`;

export class TextBox extends BaseElement {
  
  text: string;
  id: string;

  // placeholder text generated by Jeffsum.com
  constructor(text = LOREM_IPSUM) {
    super();
    this.text = text;
  }
}